Models/ErrorViewModel.cs
using System;

namespace Fibonacci.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FibonacciModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Fibonacci.Models
{
    public class FibonacciModel
    {
        public long limit { get; set; }
      
        public long Sum { get; set; }
    }
}

Controllers/FibonacciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Fibonacci.Models;

namespace Fibonacci.Controllers
{
    public class FibonacciController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(FibonacciModel model)
        {
            if (model.limit < 2 || model.limit >= 4000000)// first check limit
            {
                ViewBag.ErrorMessage = "Enter valid limit between 2 - 4000000";
            }
            else
            {
                long firstEN = 0;
                long secondEN = 2;
                long Sum = firstEN + secondEN;
                while (secondEN < model.limit)
                {
                    long thirdEN = 4 * secondEN + firstEN;
                    if (thirdEN > model.limit)
                        break;
                    firstEN = secondEN;
                    secondEN = thirdEN;
                    Sum += secondEN;
                }
                model.Sum = Sum;
            }
                return View(model);
            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Fibonacci.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Fibonacci.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Fibonacci/Index.cshtml
@model Fibonacci.Models.FibonacciModel;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Even Fibonacci terms";
}



<h2>Even Fibonacci numbers</h2> 
<div id ="center">
    @using (Html.BeginForm())
    { <fieldset > <legend style = "color:darkblue" > Enter Limit for Sum </legend>
        @Html.TextBoxFor(m => m.limit, new { @class = "form-control" }) <br/> 
        <input type = "submit" value = "Submit" name = "Enter" /> <br/> <br/> 
    <h2 style = "color:darkblue" > @Html.Label("Result is :")
        @Html.DisplayFor(m => m.Sum, new { @class = "form-control" }) </h2> </fieldset>
        }
    </div>
<div class="alert alert-danger">
    <p>@ViewBag.ErrorMessage</p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title >@ViewData["Title"] - FibonacciApp </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Fibonacci" asp-action="Index">Fibonacci</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Fibonacci - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>